name: C/C++ CI

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev libcurl4-openssl-dev

      - name: Generate configuration script
        run: autoreconf --install

      - name: Configure
        run: ./configure

      - name: Build
        run: make


