name: C/C++ CI

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: generate conf script
        run: |
          autoreconf --install

      - name: configure
        run: ./configure

      - name: build
        run: make

      - name: run tests
        run: make check

      - name: load test results
        uses: actions/upload-artifact@v4
        with:
          name: tests
          path: tests.log
